data: '/home/linjunyang/pku/data/'
logF: 'experiments/pku/'
epoch: 20
batch_size: 64
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
learning_rate: 0.0003
max_grad_norm: 10
learning_rate_decay: 0.5
start_decay_at: 4
emb_size: 512
hidden_size: 512
dec_num_layers: 3
enc_num_layers: 3
bidirectional: True
dropout: 0.2
max_time_step: 50
eval_interval: 10000
save_interval: 3000
metrics: ['bleu']
shared_vocab: False
beam_size: 12
unk: False
schedule: False
schesamp: False
length_norm: True
